[
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "7S51TM2ZIG",
    policies: {
      cancellations: [
        { amount: "665.00", deadline: "2023-11-13T23:59:00+00:00" },
      ],
    },
    price: {
      base: "665.00",
      currency: "GBP",
      total: "698.25",
      variations: {
        average: { base: "665.00" },
        changes: [
          { base: "665.00", endDate: "2023-11-15", startDate: "2023-11-14" },
        ],
      },
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: {
      description: {
        lang: "EN",
        text: "Flexible Rate, Deluxe Queen Room, 1 Queen(s), 20sqm/215sqft-29sqm/312sqft Wireless",
      },

      type: "REG",
      typeEstimated: { bedType: "QUEEN", beds: 1, category: "DELUXE_ROOM" },
    },

    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/7S51TM2ZIG",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "MAUHHBYBJC",
    policies: { cancellations: [Array] },
    price: {
      base: "705.00",
      currency: "GBP",
      total: "740.25",
      variations: [Object],
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: { description: [Object], type: "YBK", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/MAUHHBYBJC",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "0VASTW2P92",
    policies: { cancellations: [Array] },
    price: {
      base: "745.00",
      currency: "GBP",
      total: "782.25",
      variations: [Object],
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: { description: [Object], type: "REG", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/0VASTW2P92",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "E9RF317XH1",
    policies: { cancellations: [Array] },
    price: {
      base: "775.00",
      currency: "GBP",
      total: "813.75",
      variations: [Object],
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: { description: [Object], type: "REG", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/E9RF317XH1",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "HH28GCC1Y1",
    policies: { cancellations: [Array] },
    price: {
      base: "785.00",
      currency: "GBP",
      total: "824.25",
      variations: [Object],
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: { description: [Object], type: "YBK", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/HH28GCC1Y1",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "ZSOGNUP3BF",
    policies: { cancellations: [Array] },
    price: {
      base: "815.00",
      currency: "GBP",
      total: "855.75",
      variations: [Object],
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: { description: [Object], type: "REG", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/ZSOGNUP3BF",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "XJQDM3UMWQ",
    policies: { cancellations: [Array] },
    price: {
      base: "815.00",
      currency: "GBP",
      total: "855.75",
      variations: [Object],
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: { description: [Object], type: "YBK", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/XJQDM3UMWQ",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "DCE3O9HZFQ",
    policies: { cancellations: [Array] },
    price: {
      base: "895.00",
      currency: "GBP",
      total: "939.75",
      variations: [Object],
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: { description: [Object], type: "YBK", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/DCE3O9HZFQ",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "N1SX00LIP5",
    policies: { cancellations: [Array] },
    price: {
      base: "925.00",
      currency: "GBP",
      total: "971.25",
      variations: [Object],
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: { description: [Object], type: "REG", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/N1SX00LIP5",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "TFA4XZGJYO",
    policies: { cancellations: [Array] },
    price: {
      base: "985.00",
      currency: "GBP",
      total: "1034.25",
      variations: [Object],
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: { description: [Object], type: "REG", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/TFA4XZGJYO",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "HT2W0DBB3H",
    policies: { cancellations: [Array] },
    price: {
      base: "1005.00",
      currency: "GBP",
      total: "1055.25",
      variations: [Object],
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: { description: [Object], type: "REG", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/HT2W0DBB3H",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "BY2SW66572",
    policies: { cancellations: [Array] },
    price: {
      base: "1185.00",
      currency: "GBP",
      total: "1244.25",
      variations: [Object],
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: { description: [Object], type: "REG", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/BY2SW66572",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "0BL06K06KA",
    policies: { cancellations: [Array] },
    price: {
      base: "1205.00",
      currency: "GBP",
      total: "1265.25",
      variations: [Object],
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: { description: [Object], type: "REG", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/0BL06K06KA",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "WIKSCT8LS8",
    policies: { cancellations: [Array] },
    price: {
      base: "1940.00",
      currency: "GBP",
      total: "2037.00",
      variations: [Object],
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: { description: [Object], type: "REG", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/WIKSCT8LS8",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "TFBISIVR0H",
    policies: { cancellations: [Array] },
    price: {
      base: "2440.00",
      currency: "GBP",
      total: "2562.00",
      variations: [Object],
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: { description: [Object], type: "REG", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/TFBISIVR0H",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "980KVXDQTS",
    policies: { cancellations: [Array] },
    price: {
      base: "2940.00",
      currency: "GBP",
      total: "3087.00",
      variations: [Object],
    },
    rateCode: "RAC",
    rateFamilyEstimated: { code: "BAR", type: "P" },
    room: { description: [Object], type: "REG", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/980KVXDQTS",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "294TEK570H",
    policies: { cancellations: [Array] },
    price: {
      base: "532.00",
      currency: "GBP",
      total: "558.60",
      variations: [Object],
    },
    rateCode: "S9R",
    rateFamilyEstimated: { code: "SRS", type: "C" },
    room: { description: [Object], type: "XMI", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/294TEK570H",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "S47XAD6CLM",
    policies: { cancellations: [Array] },
    price: {
      base: "596.00",
      currency: "GBP",
      total: "625.80",
      variations: [Object],
    },
    rateCode: "S9R",
    rateFamilyEstimated: { code: "SRS", type: "C" },
    room: { description: [Object], type: "XMI", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/S47XAD6CLM",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "FK044K8IRS",
    policies: { cancellations: [Array] },
    price: {
      base: "620.00",
      currency: "GBP",
      total: "651.00",
      variations: [Object],
    },
    rateCode: "S9R",
    rateFamilyEstimated: { code: "SRS", type: "C" },
    room: { description: [Object], type: "XMI", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/FK044K8IRS",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "J0XF6GTA6G",
    policies: { cancellations: [Array] },
    price: {
      base: "652.00",
      currency: "GBP",
      total: "684.60",
      variations: [Object],
    },
    rateCode: "S9R",
    rateFamilyEstimated: { code: "SRS", type: "C" },
    room: { description: [Object], type: "XMI", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/J0XF6GTA6G",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "Q3PPBA1W21",
    policies: { cancellations: [Array] },
    price: {
      base: "740.00",
      currency: "GBP",
      total: "777.00",
      variations: [Object],
    },
    rateCode: "S9R",
    rateFamilyEstimated: { code: "SRS", type: "C" },
    room: { description: [Object], type: "XMI", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/Q3PPBA1W21",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "002O8IKZZY",
    policies: { cancellations: [Array] },
    price: {
      base: "788.00",
      currency: "GBP",
      total: "827.40",
      variations: [Object],
    },
    rateCode: "S9R",
    rateFamilyEstimated: { code: "SRS", type: "C" },
    room: { description: [Object], type: "XMI", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/002O8IKZZY",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "19A1F4EAE2",
    policies: { cancellations: [Array] },
    price: {
      base: "804.00",
      currency: "GBP",
      total: "844.20",
      variations: [Object],
    },
    rateCode: "S9R",
    rateFamilyEstimated: { code: "SRS", type: "C" },
    room: { description: [Object], type: "XMI", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/19A1F4EAE2",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "5TIM8L8G5M",
    policies: { cancellations: [Array] },
    price: {
      base: "948.00",
      currency: "GBP",
      total: "995.40",
      variations: [Object],
    },
    rateCode: "S9R",
    rateFamilyEstimated: { code: "SRS", type: "C" },
    room: { description: [Object], type: "XMI", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/5TIM8L8G5M",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "QG9VIV796M",
    policies: { cancellations: [Array] },
    price: {
      base: "964.00",
      currency: "GBP",
      total: "1012.20",
      variations: [Object],
    },
    rateCode: "S9R",
    rateFamilyEstimated: { code: "SRS", type: "C" },
    room: { description: [Object], type: "XMI", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/QG9VIV796M",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "JX0243DNCN",
    policies: { cancellations: [Array] },
    price: {
      base: "1552.00",
      currency: "GBP",
      total: "1629.60",
      variations: [Object],
    },
    rateCode: "S9R",
    rateFamilyEstimated: { code: "SRS", type: "C" },
    room: { description: [Object], type: "XMI", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/JX0243DNCN",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "V7FR37WAHL",
    policies: { cancellations: [Array] },
    price: {
      base: "1952.00",
      currency: "GBP",
      total: "2049.60",
      variations: [Object],
    },
    rateCode: "S9R",
    rateFamilyEstimated: { code: "SRS", type: "C" },
    room: { description: [Object], type: "XMI", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/V7FR37WAHL",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "ECYVYRGO3D",
    policies: { cancellations: [Array] },
    price: {
      base: "2352.00",
      currency: "GBP",
      total: "2469.60",
      variations: [Object],
    },
    rateCode: "S9R",
    rateFamilyEstimated: { code: "SRS", type: "C" },
    room: { description: [Object], type: "XMI", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/ECYVYRGO3D",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "HZW027RY3L",
    policies: { cancellations: [Array] },
    price: {
      base: "4916.00",
      currency: "GBP",
      total: "5161.80",
      variations: [Object],
    },
    rateCode: "S9R",
    rateFamilyEstimated: { code: "SRS", type: "C" },
    room: { description: [Object], type: "XMI", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/HZW027RY3L",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "CZK8IO8B8Z",
    policies: { cancellations: [Array] },
    price: {
      base: "1025.00",
      currency: "GBP",
      total: "1076.25",
      variations: [Object],
    },
    rateCode: "B4K",
    room: { description: [Object], type: "YBK", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/CZK8IO8B8Z",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "VOH6LBYPZT",
    policies: { cancellations: [Array] },
    price: {
      base: "1245.00",
      currency: "GBP",
      total: "1307.25",
      variations: [Object],
    },
    rateCode: "B4K",
    room: { description: [Object], type: "YBK", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/VOH6LBYPZT",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "7ALY0SQHW0",
    policies: { cancellations: [Array] },
    price: {
      base: "1045.00",
      currency: "GBP",
      total: "1097.25",
      variations: [Object],
    },
    rateCode: "B4K",
    room: { description: [Object], type: "YBK", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/7ALY0SQHW0",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "OYNQPC56QR",
    policies: { cancellations: [Array] },
    price: {
      base: "1225.00",
      currency: "GBP",
      total: "1286.25",
      variations: [Object],
    },
    rateCode: "B4K",
    room: { description: [Object], type: "YBK", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/OYNQPC56QR",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "BCXNR19KRR",
    policies: { cancellations: [Array] },
    price: {
      base: "1980.00",
      currency: "GBP",
      total: "2079.00",
      variations: [Object],
    },
    rateCode: "B4K",
    room: { description: [Object], type: "YBK", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/BCXNR19KRR",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "JH4KHQLHFH",
    policies: { cancellations: [Array] },
    price: {
      base: "2480.00",
      currency: "GBP",
      total: "2604.00",
      variations: [Object],
    },
    rateCode: "B4K",
    room: { description: [Object], type: "YBK", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/JH4KHQLHFH",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "UWCFEYTDGT",
    policies: { cancellations: [Array] },
    price: {
      base: "2980.00",
      currency: "GBP",
      total: "3129.00",
      variations: [Object],
    },
    rateCode: "B4K",
    room: { description: [Object], type: "YBK", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/UWCFEYTDGT",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "XO9MSOT3EK",
    policies: { cancellations: [Array] },
    price: {
      base: "6185.00",
      currency: "GBP",
      total: "6494.25",
      variations: [Object],
    },
    rateCode: "B4K",
    room: { description: [Object], type: "YBK", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/XO9MSOT3EK",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "A9LFP3H2JR",
    policies: { cancellations: [Array] },
    price: {
      base: "895.00",
      currency: "GBP",
      total: "939.75",
      variations: [Object],
    },
    rateCode: "MAJ",
    room: { description: [Object], type: "XXF", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/A9LFP3H2JR",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "CZOWBFG7JN",
    policies: { cancellations: [Array] },
    price: {
      base: "785.00",
      currency: "GBP",
      total: "824.25",
      variations: [Object],
    },
    rateCode: "MAJ",
    room: { description: [Object], type: "XXF", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/CZOWBFG7JN",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "DFY5CX60RC",
    policies: { cancellations: [Array] },
    price: {
      base: "965.00",
      currency: "GBP",
      total: "1013.25",
      variations: [Object],
    },
    rateCode: "MAJ",
    room: { description: [Object], type: "XXF", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/DFY5CX60RC",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "4JLP60RW3O",
    policies: { cancellations: [Array] },
    price: {
      base: "1045.00",
      currency: "GBP",
      total: "1097.25",
      variations: [Object],
    },
    rateCode: "MAJ",
    room: { description: [Object], type: "XXF", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/4JLP60RW3O",
  },
  {
    checkInDate: "2023-11-14",
    checkOutDate: "2023-11-15",
    guests: { adults: 2 },
    id: "KIXX4UEWSP",
    policies: { cancellations: [Array] },
    price: {
      base: "1980.00",
      currency: "GBP",
      total: "2079.00",
      variations: [Object],
    },
    rateCode: "MAJ",
    room: { description: [Object], type: "XXF", typeEstimated: [Object] },
    self: "https://test.api.amadeus.com/v3/shopping/hotel-offers/KIXX4UEWSP",
  },
];
